blueprint:
  name: Clavier Zigbee ↔️ Alarmo (validation par Alarmo)
  description: >
    Synchronise l'état d'un clavier Zigbee2MQTT avec un panneau de contrôle Alarmo,
    sans valider les codes PIN côté blueprint (c'est Alarmo qui les valide).
  domain: automation
  input:
    mqtt_topic_etat_clavier:
      name: Topic MQTT d'état du clavier Zigbee2MQTT
      description: "Exemple : zigbee2mqtt/Clavier"
      selector:
        text:
    mqtt_topic_commande_clavier:
      name: Topic MQTT de commande du clavier Zigbee2MQTT
      description: "Exemple : zigbee2mqtt/Clavier/set"
      selector:
        text:
    panneau_alarme:
      name: Panneau de contrôle Alarmo
      selector:
        entity:
          domain: alarm_control_panel

trigger:
  - platform: state
    entity_id: !input panneau_alarme
    id: changement_etat_alarme

  - platform: mqtt
    topic: !input mqtt_topic_etat_clavier
    id: commande_clavier

action:
  - choose:
      - conditions:
          - condition: trigger
            id: changement_etat_alarme
        sequence:
          - service: mqtt.publish
            data:
              topic: !input mqtt_topic_commande_clavier
              payload: >
                {% set etat = trigger.to_state.state %}
                {% if etat == 'armed_away' %}
                  {"arm_mode":{"mode":"arm_all_zones"}}
                {% elif etat == 'armed_home' %}
                  {"arm_mode":{"mode":"arm_day_zones"}}
                {% elif etat == 'armed_night' %}
                  {"arm_mode":{"mode":"arm_night_zones"}}
                {% elif etat == 'disarmed' %}
                  {"arm_mode":{"mode":"disarm"}}
                {% elif etat == 'arming' %}
                  {% if trigger.to_state.attributes.next_state == 'armed_home' %}
                    {"arm_mode":{"mode":"arm_day_zones"}}
                  {% elif trigger.to_state.attributes.next_state == 'armed_away' %}
                    {"arm_mode":{"mode":"exit_delay"}}
                  {% endif %}
                {% endif %}

      - conditions:
          - condition: trigger
            id: commande_clavier
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: >
                      {{ trigger.payload_json.action_transaction is defined and trigger.payload_json.action_code is defined }}
                sequence:
                  - service: mqtt.publish
                    data:
                      topic: !input mqtt_topic_commande_clavier
                      payload: >
                        {
                          "arm_mode": {
                            "transaction": "{{ trigger.payload_json.action_transaction }}",
                            "mode": "{{ trigger.payload_json.action | trim }}"
                          }
                        }

                  - choose:
                      - conditions:
                          - condition: template
                            value_template: "{{ trigger.payload_json.action == 'arm_all_zones' }}"
                        sequence:
                          - service: alarm_control_panel.alarm_arm_away
                            target:
                              entity_id: !input panneau_alarme
                            data:
                              code: "{{ trigger.payload_json.action_code }}"

                      - conditions:
                          - condition: template
                            value_template: "{{ trigger.payload_json.action == 'arm_day_zones' }}"
                        sequence:
                          - service: alarm_control_panel.alarm_arm_home
                            target:
                              entity_id: !input panneau_alarme
                            data:
                              code: "{{ trigger.payload_json.action_code }}"

                      - conditions:
                          - condition: template
                            value_template: "{{ trigger.payload_json.action == 'arm_night_zones' }}"
                        sequence:
                          - service: alarm_control_panel.alarm_arm_night
                            target:
                              entity_id: !input panneau_alarme
                            data:
                              code: "{{ trigger.payload_json.action_code }}"

                      - conditions:
                          - condition: template
                            value_template: "{{ trigger.payload_json.action == 'disarm' }}"
                        sequence:
                          - service: alarm_control_panel.alarm_disarm
                            target:
                              entity_id: !input panneau_alarme
                            data:
                              code: "{{ trigger.payload_json.action_code }}"
